# Generated by Django 2.2.2 on 2019-06-30 22:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hy', models.CharField(db_index=True, max_length=300, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=300, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=300, verbose_name='Title:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_en', unique=True)),
                ('author_hy', models.TextField(blank=True, db_index=True, verbose_name='Հեղինակ:')),
                ('author_ru', models.TextField(blank=True, db_index=True, verbose_name='Автор:')),
                ('author_en', models.TextField(blank=True, db_index=True, verbose_name='Author:')),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/', verbose_name='Նկար:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Բլոգ',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_dey_hy', models.CharField(db_index=True, max_length=150, verbose_name='Շաբաթվա օրը:')),
                ('week_dey_ru', models.CharField(db_index=True, max_length=150, verbose_name='День недели:')),
                ('week_dey_en', models.CharField(db_index=True, max_length=150, verbose_name='The day of the week:')),
                ('date_hy', models.CharField(db_index=True, max_length=150, verbose_name='Ամսաթիվը:')),
                ('date_ru', models.CharField(db_index=True, max_length=150, verbose_name='Дата:')),
                ('date_en', models.CharField(db_index=True, max_length=150, verbose_name='Date:')),
                ('title_hy', models.CharField(db_index=True, max_length=300, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=300, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=300, verbose_name='Title:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_hy', unique=True)),
                ('from_time', models.TimeField(verbose_name='Սկիզբը:')),
                ('to_time', models.TimeField(verbose_name='Ավարտը:')),
                ('image', models.ImageField(blank=True, upload_to='broadcasts/%Y/%m/%d/', verbose_name='Նկար:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Հաղորդացանցեր',
                'ordering': ['date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appstore_url', models.CharField(db_index=True, max_length=500, verbose_name='App Store-ի Լինք:')),
                ('playmarket_url', models.CharField(db_index=True, max_length=500, verbose_name='Play Market-ի Լինք:')),
                ('facebook', models.CharField(db_index=True, max_length=500, verbose_name='Facebook:')),
                ('yuotube', models.CharField(db_index=True, max_length=500, verbose_name='YouTube:')),
                ('soundcloud', models.CharField(db_index=True, max_length=500, verbose_name='SoundCloud:')),
                ('text_hy', models.TextField(db_index=True, max_length=500, verbose_name='© Տեքստ:')),
                ('text_ru', models.TextField(db_index=True, max_length=500, verbose_name='© Текст:')),
                ('text_en', models.TextField(db_index=True, max_length=500, verbose_name='© Text:')),
            ],
            options={
                'verbose_name_plural': 'Վերջաբան',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_picture', models.ImageField(blank=True, upload_to='general/%Y/%m/%d/', verbose_name='Նկար:')),
                ('yt_url', models.CharField(db_index=True, max_length=1000, verbose_name='YT URL:')),
            ],
            options={
                'verbose_name_plural': 'Գլխավոր էջի նկար և տեսահոլովակ',
            },
        ),
        migrations.CreateModel(
            name='GeneralVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_1', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
                ('url_2', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
                ('url_3', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
                ('url_4', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
            ],
            options={
                'verbose_name_plural': 'Գլխավոր էջի տեսահոլովակներ',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1_hy', models.CharField(db_index=True, max_length=20, verbose_name='Հարցազրույցներ:')),
                ('title_1_ru', models.CharField(db_index=True, max_length=20, verbose_name='Интервью:')),
                ('title_1_en', models.CharField(db_index=True, max_length=20, verbose_name='Interviews:')),
                ('title_2_hy', models.CharField(db_index=True, max_length=20, verbose_name='Ծրագրեր:')),
                ('title_2_ru', models.CharField(db_index=True, max_length=20, verbose_name='Программы:')),
                ('title_2_en', models.CharField(db_index=True, max_length=20, verbose_name='Programs:')),
                ('title_3_hy', models.CharField(db_index=True, max_length=20, verbose_name='Հաղորդացանց:')),
                ('title_3_ru', models.CharField(db_index=True, max_length=20, verbose_name='Трансляций:')),
                ('title_3_en', models.CharField(db_index=True, max_length=20, verbose_name='Broadcasts:')),
                ('title_4_hy', models.CharField(db_index=True, max_length=20, verbose_name='Բլոգ:')),
                ('title_4_ru', models.CharField(db_index=True, max_length=20, verbose_name='Блог:')),
                ('title_4_en', models.CharField(db_index=True, max_length=20, verbose_name='Blog:')),
                ('title_5_hy', models.CharField(db_index=True, max_length=20, verbose_name='Մեր մասին:')),
                ('title_5_ru', models.CharField(db_index=True, max_length=20, verbose_name='О нас:')),
                ('title_5_en', models.CharField(db_index=True, max_length=20, verbose_name='About us:')),
                ('listen_url', models.CharField(db_index=True, max_length=500, verbose_name='Լսելու Լինք:')),
                ('watch_url', models.CharField(db_index=True, max_length=500, verbose_name='Դիտելու Լինք:')),
            ],
            options={
                'verbose_name_plural': 'Ցանկի կետերը',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hy', models.CharField(db_index=True, max_length=300, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=300, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=300, verbose_name='Title:')),
                ('body_hy', models.TextField(blank=True, db_index=True, verbose_name='Մարմին:')),
                ('body_ru', models.TextField(blank=True, db_index=True, verbose_name='Тело:')),
                ('body_en', models.TextField(blank=True, db_index=True, verbose_name='Body:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_hy', unique=True)),
                ('image', models.ImageField(blank=True, upload_to='interviews/%Y/%m/%d/', verbose_name='Նկար:')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Հարցազրույցներ',
                'ordering': ['-date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Ourme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hy', models.CharField(db_index=True, max_length=150, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=150, verbose_name='Title:')),
                ('body_hy', models.TextField(db_index=True, max_length=20000, verbose_name='Մարմին:')),
                ('body_ru', models.TextField(db_index=True, max_length=20000, verbose_name='Тело:')),
                ('body_en', models.TextField(db_index=True, max_length=20000, verbose_name='Body:')),
                ('image', models.ImageField(blank=True, upload_to='ourme/%Y/%m/%d/', verbose_name='Նկար:')),
            ],
            options={
                'verbose_name_plural': 'Մեր մասին',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
            ],
            options={
                'verbose_name_plural': 'Գործընկերոջ նկար և լինք',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hy', models.CharField(db_index=True, max_length=300, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=300, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=300, verbose_name='Title:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_hy', unique=True)),
                ('author_hy', models.TextField(blank=True, db_index=True, verbose_name='Հեղինակ:')),
                ('author_ru', models.TextField(blank=True, db_index=True, verbose_name='Автор:')),
                ('author_en', models.TextField(blank=True, db_index=True, verbose_name='Author:')),
                ('image', models.ImageField(blank=True, upload_to='programs/%Y/%m/%d/', verbose_name='Նկար:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ծրագրեր',
                'ordering': ['-date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slider/%Y/%m/%d/', verbose_name='Նկար:')),
            ],
            options={
                'verbose_name_plural': 'Սլայդերի նկարներ',
            },
        ),
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hy', models.CharField(db_index=True, max_length=20, verbose_name='Վերնագիր:')),
                ('title_ru', models.CharField(db_index=True, max_length=20, verbose_name='Заголовок:')),
                ('title_en', models.CharField(db_index=True, max_length=20, verbose_name='Title:')),
                ('body_hy', models.TextField(db_index=True, max_length=70, verbose_name='Մարմին:')),
                ('body_ru', models.TextField(db_index=True, max_length=70, verbose_name='Тело:')),
                ('body_en', models.TextField(db_index=True, max_length=70, verbose_name='Body:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_hy', unique=True)),
                ('image', models.ImageField(blank=True, upload_to='topnews/%Y/%m/%d/', verbose_name='Նկար:')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='Լինք:')),
            ],
            options={
                'verbose_name_plural': 'Թոփ նորություններ',
            },
        ),
    ]
