# Generated by Django 2.2.2 on 2019-06-30 22:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_en', unique=True),
        ),
    ]
