# Generated by Django 2.2.2 on 2019-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190701_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='body_en',
            field=models.TextField(blank=True, db_index=True, verbose_name='Body:'),
        ),
        migrations.AddField(
            model_name='programs',
            name='body_hy',
            field=models.TextField(blank=True, db_index=True, verbose_name='Մարմին:'),
        ),
        migrations.AddField(
            model_name='programs',
            name='body_ru',
            field=models.TextField(blank=True, db_index=True, verbose_name='Тело:'),
        ),
        migrations.AddField(
            model_name='programs',
            name='program_name_en',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Programm name:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='program_name_hy',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Ծրագրի անուն:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='program_name_ru',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя программы:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topnews',
            name='body_en',
            field=models.TextField(db_index=True, max_length=660, verbose_name='Body:'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='body_hy',
            field=models.TextField(db_index=True, max_length=660, verbose_name='Մարմին:'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='body_ru',
            field=models.TextField(db_index=True, max_length=660, verbose_name='Тело:'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='title_en',
            field=models.CharField(db_index=True, max_length=660, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='title_hy',
            field=models.CharField(db_index=True, max_length=660, verbose_name='Վերնագիր:'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=660, verbose_name='Заголовок:'),
        ),
    ]
