# Generated by Django 2.2.2 on 2019-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190701_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='url',
            new_name='url_1',
        ),
        migrations.AddField(
            model_name='partners',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='url_2',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='url_3',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='url_4',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
    ]
