# Generated by Django 2.2.2 on 2019-07-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190701_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='image_1',
            new_name='image',
        ),
    ]
