# Generated by Django 2.2.2 on 2019-07-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190701_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='image',
            new_name='image_1',
        ),
    ]
