# Generated by Django 2.2.2 on 2019-07-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190701_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='url_2',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='url_3',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='url_4',
        ),
    ]
