# Generated by Django 2.2.2 on 2019-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190701_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='partners/%Y/%m/%d/', verbose_name='Նկար:'),
        ),
        migrations.AddField(
            model_name='partners',
            name='url_2',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='url_3',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='url_4',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Լինք:'),
            preserve_default=False,
        ),
    ]
