# Generated by Django 2.2.2 on 2019-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190701_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='text_en',
            field=models.TextField(db_index=True, max_length=530, verbose_name='© Text:'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='text_hy',
            field=models.TextField(db_index=True, max_length=530, verbose_name='© Տեքստ:'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='text_ru',
            field=models.TextField(db_index=True, max_length=530, verbose_name='© Текст:'),
        ),
    ]
