# Generated by Django 2.2.2 on 2019-07-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190701_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_dey_hy', models.CharField(db_index=True, max_length=150, verbose_name='Շաբաթվա օրը:')),
                ('week_dey_ru', models.CharField(db_index=True, max_length=150, verbose_name='День недели:')),
                ('week_dey_en', models.CharField(db_index=True, max_length=150, verbose_name='The day of the week:')),
                ('date_hy', models.CharField(db_index=True, max_length=150, verbose_name='Ամսաթիվը:')),
                ('date_ru', models.CharField(db_index=True, max_length=150, verbose_name='Дата:')),
                ('date_en', models.CharField(db_index=True, max_length=150, verbose_name='Date:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ամիս֊ամսաթիվ',
                'ordering': ['date_pub'],
            },
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='date_hy',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='date_ru',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='week_dey_en',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='week_dey_hy',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='week_dey_ru',
        ),
        migrations.AlterField(
            model_name='interview',
            name='body_en',
            field=models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Body:'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='body_hy',
            field=models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Մարմին:'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='body_ru',
            field=models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Тело:'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='broadcastdate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.BroadcastDate'),
            preserve_default=False,
        ),
    ]
