# Generated by Django 2.2.2 on 2019-07-03 11:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190703_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastdate',
            options={'ordering': ['date_pub'], 'verbose_name': 'Ամիս֊ամսաթիվ', 'verbose_name_plural': 'Ամիս֊ամսաթիվ'},
        ),
        migrations.AddField(
            model_name='broadcastdate',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='date_en', unique=True),
            preserve_default=False,
        ),
    ]
