# Generated by Django 2.2.2 on 2019-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190703_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
