# Generated by Django 2.2.2 on 2019-07-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_broadcast_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ourme',
            new_name='AboutUs',
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='broadcastdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Հաղորդացանցեր', to='mainapp.BroadcastDate'),
        ),
    ]
