# Generated by Django 2.2.2 on 2019-07-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190703_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='mail',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='Էլեկտրոնային հասցե։'),
            preserve_default=False,
        ),
    ]
