# Generated by Django 2.2.2 on 2019-07-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_footer_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_hy',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_ru',
        ),
    ]
