# Generated by Django 2.2.2 on 2019-07-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190703_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_pub'], 'verbose_name_plural': 'Բլոգ'},
        ),
    ]
